---
- hosts: localhost
  name: build boxes
  connection: local
  gather_facts: no

  tasks:
    - name: create directories
      file: path="{{ builder_dir }}/{{ item.name }}" state=directory
      with_items: virt_builder_images

    - name: create empty virt-builder index
      command: touch {{ builder_dir }}/index creates={{ builder_dir }}/index

    - name: copy virt-builder files to {{ builder_dir }}
      copy: src=files/{{ item }} dest={{ builder_dir }}//{{ item|basename }}
      with_items:
        - sudoers
        - vagrant.pub

    - name: template misc configuration files
      template: src=files/{{ item.src }} dest={{ builder_dir }}/{{ item.dest}}
      with_items:
        - { src: password.j2,        dest: passwrd }
        - { src: vagrant-user.sh.j2, dest: vagrant-user.sh }

    - name: template vagrant metadata.json
      template: src=files/metadata.j2 dest={{ builder_dir }}/{{ item.name }}/metadata.json
      with_items: virt_builder_images

    - name: copy vagrantfile
      with_items: virt_builder_images
      copy: src=files/Vagrantfile dest={{ builder_dir }}/{{ item.name }}/Vagrantfile

    - name: build images
      with_items: virt_builder_images
      environment:
        LIBGUESTFS_BACKEND: direct
      register: virt_builder
      command: >
        chdir={{builder_dir}}
        creates={{ builder_dir }}/{{ item.name }}/box.img
        virt-builder {{ item.name }}
        --output {{ item.name }}/box.img
        --install {{ ",".join(item.install) | default( ",".join(virt_builder_install )) }}
        {{ item.options | default("") }}
        {{ virt_builder_options }}

    - name: sparsify the images
      with_items: virt_builder_images
      environment:
        LIBGUESTFS_BACKEND: direct
      command: >
        chdir={{ builder_dir }} virt-sparsify --in-place {{ item.name }}/box.img

# https://github.com/pradels/vagrant-libvirt/tree/master/example_box
    - name: create vagrant box
      with_items: virt_builder_images
      when: virt_builder.changed
      command: >
        chdir={{ builder_dir }}/{{ item.name }}
        tar czf {{ builder_dir }}/{{ item.name }}.box metadata.json Vagrantfile box.img

    - name: get installed boxes
      command: vagrant box list
      register: vagrant_boxes

    - name: install new boxes
      with_items: virt_builder_images
      when: "item.name not in vagrant_boxes.stdout"
      command: vagrant box add --name {{ item.name }} {{ builder_dir }}/{{ item.name }}.box

    - name: upgrade existing boxes
      with_items: virt_builder_images
      when: "item.name in vagrant_boxes.stdout"
      command: vagrant box upgrade --box {{ item.name }} {{ builder_dir }}/{{ item.name }}.box
