---
- hosts: localhost
  name: build boxes
  connection: local
  gather_facts: no

  tasks:
    - name: create directories
      file: path="{{ builder_dir }}/{{ item }}" state=directory
      with_items: virt_builder_images

    - name: create empty virt-builder index
      command: touch {{ builder_dir }}/index creates={{ builder_dir }}/index

    - name: copy virt-builder files to {{ builder_dir }}
      copy: src={{ item }} dest={{ builder_dir }}//{{ item|basename }}
      with_items:
        - bootstrap.yml
        - hosts
        - group_vars/all
        - host_vars/localhost
        - password
        - sudoers
        - vagrant.pub

    - name: create vagrant metadata.json
      template: src=metadata.j2 dest={{ builder_dir }}/{{ item }}/metadata.json
      with_items: virt_builder_images

    - name: copy vagrantfile
      with_items: virt_builder_images
      copy: src=Vagrantfile dest={{builder_dir}}/{{item}}/Vagrantfile

    - name: build images
      with_items: virt_builder_images
      environment:
        LIBGUESTFS_BACKEND: direct
      command: >
        chdir={{builder_dir}}
        virt-builder {{item}}
        --output {{item}}/box.img
        --mkdir /root/host_vars
        --mkdir /root/group_vars
        --upload {{ builder_dir }}/sudoers:/root
        --upload {{ builder_dir }}/vagrant.pub:/root
        --upload {{ builder_dir }}/hosts:/root
        --upload {{ builder_dir }}/all:/root/group_vars
        --upload {{ builder_dir }}/localhost:/root/host_vars
        --upload {{ builder_dir }}/bootstrap.yml:/root
        {{ virt_builder_options }}
        {{ extra_virt_builder_options }}

    - name: sparsify the images
      with_items: virt_builder_images
      command: >
        chdir={{builder_dir}} virt-sparsify --in-place {{item}}/box.img

# https://github.com/pradels/vagrant-libvirt/tree/master/example_box
    - name: create vagrant box
      with_items: virt_builder_images
      command: >
        chdir={{builder_dir}}/{{item}}
        tar czf {{builder_dir}}/{{item}}.box metadata.json Vagrantfile box.img

    - name: get installed boxes
      command: vagrant box list
      register: vagrant_boxes

    - name: install new boxes
      with_items: virt_builder_images
      when: "item not in vagrant_boxes.stdout"
      command: vagrant box add --name {{item}} {{builder_dir}}/{{item}}.box

    - name: upgrade existing boxes
      with_items: virt_builder_images
      when: "item in vagrant_boxes.stdout"
      command: vagrant box upgrade --box {{item}} {{builder_dir}}/{{item}}.box
